postgresConnectionString: "postgres://metisDbUser:metisPassword@postgres:5432/metisDb"

queries:
  - name: "Databases"
    sql: >
      SELECT oid as db_id,
      datname as database_name,
      pg_database_size(datname) / 1024 as database_size_kb,
      pg_size_pretty(pg_database_size(datname)) as db_size
      FROM pg_database
      WHERE datistemplate = false;

  - name: "Tables Size"
    sql: >
      SELECT relname as table_name,
      pg_table_size(oid) as table_size
      from pg_class
      WHERE relkind = 'r'
